// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerTransferDataProtoc.proto

package com.handsome.landlords.entity;

public final class ServerTransferData {
	private ServerTransferData() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
				(com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface ServerTransferDataProtocOrBuilder extends
			// @@protoc_insertion_point(interface_extends:com.handsome.landlords.entity.ServerTransferDataProtoc)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string code = 1;</code>
		 */
		String getCode();

		/**
		 * <code>string code = 1;</code>
		 */
		com.google.protobuf.ByteString
		getCodeBytes();

		/**
		 * <code>string data = 2;</code>
		 */
		String getData();

		/**
		 * <code>string data = 2;</code>
		 */
		com.google.protobuf.ByteString
		getDataBytes();

		/**
		 * <code>string info = 3;</code>
		 */
		String getInfo();

		/**
		 * <code>string info = 3;</code>
		 */
		com.google.protobuf.ByteString
		getInfoBytes();
	}

	/**
	 * Protobuf type {@code com.handsome.landlords.entity.ServerTransferDataProtoc}
	 */
	public static final class ServerTransferDataProtoc extends
			com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:com.handsome.landlords.entity.ServerTransferDataProtoc)
			ServerTransferDataProtocOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use ServerTransferDataProtoc.newBuilder() to construct.
		private ServerTransferDataProtoc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private ServerTransferDataProtoc() {
			code_ = "";
			data_ = "";
			info_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private ServerTransferDataProtoc(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
					com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							String s = input.readStringRequireUtf8();

							code_ = s;
							break;
						}
						case 18: {
							String s = input.readStringRequireUtf8();

							data_ = s;
							break;
						}
						case 26: {
							String s = input.readStringRequireUtf8();

							info_ = s;
							break;
						}
						default: {
							if (!parseUnknownFieldProto3(
									input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return com.handsome.landlords.entity.ServerTransferData.internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return com.handsome.landlords.entity.ServerTransferData.internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc.class, com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc.Builder.class);
		}

		public static final int CODE_FIELD_NUMBER = 1;
		private volatile Object code_;

		/**
		 * <code>string code = 1;</code>
		 */
		public String getCode() {
			Object ref = code_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				code_ = s;
				return s;
			}
		}

		/**
		 * <code>string code = 1;</code>
		 */
		public com.google.protobuf.ByteString
		getCodeBytes() {
			Object ref = code_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				code_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DATA_FIELD_NUMBER = 2;
		private volatile Object data_;

		/**
		 * <code>string data = 2;</code>
		 */
		public String getData() {
			Object ref = data_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				data_ = s;
				return s;
			}
		}

		/**
		 * <code>string data = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getDataBytes() {
			Object ref = data_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				data_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int INFO_FIELD_NUMBER = 3;
		private volatile Object info_;

		/**
		 * <code>string info = 3;</code>
		 */
		public String getInfo() {
			Object ref = info_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				info_ = s;
				return s;
			}
		}

		/**
		 * <code>string info = 3;</code>
		 */
		public com.google.protobuf.ByteString
		getInfoBytes() {
			Object ref = info_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
								(String) ref);
				info_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) return true;
			if (isInitialized == 0) return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getCodeBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
			}
			if (!getDataBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
			}
			if (!getInfoBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, info_);
			}
			unknownFields.writeTo(output);
		}

		@Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) return size;

			size = 0;
			if (!getCodeBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
			}
			if (!getDataBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
			}
			if (!getInfoBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, info_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc)) {
				return super.equals(obj);
			}
			com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc other = (com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc) obj;

			boolean result = true;
			result = result && getCode()
					.equals(other.getCode());
			result = result && getData()
					.equals(other.getData());
			result = result && getInfo()
					.equals(other.getInfo());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + CODE_FIELD_NUMBER;
			hash = (53 * hash) + getCode().hashCode();
			hash = (37 * hash) + DATA_FIELD_NUMBER;
			hash = (53 * hash) + getData().hashCode();
			hash = (37 * hash) + INFO_FIELD_NUMBER;
			hash = (53 * hash) + getInfo().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input);
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
					? new Builder() : new Builder().mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.handsome.landlords.entity.ServerTransferDataProtoc}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:com.handsome.landlords.entity.ServerTransferDataProtoc)
				com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtocOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return com.handsome.landlords.entity.ServerTransferData.internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return com.handsome.landlords.entity.ServerTransferData.internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc.class, com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc.Builder.class);
			}

			// Construct using com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
						.alwaysUseFieldBuilders) {
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				code_ = "";

				data_ = "";

				info_ = "";

				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return com.handsome.landlords.entity.ServerTransferData.internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_descriptor;
			}

			@Override
			public com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc getDefaultInstanceForType() {
				return com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc.getDefaultInstance();
			}

			@Override
			public com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc build() {
				com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc buildPartial() {
				com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc result = new com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc(this);
				result.code_ = code_;
				result.data_ = data_;
				result.info_ = info_;
				onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@Override
			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			@Override
			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@Override
			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc) {
					return mergeFrom((com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc other) {
				if (other == com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc.getDefaultInstance())
					return this;
				if (!other.getCode().isEmpty()) {
					code_ = other.code_;
					onChanged();
				}
				if (!other.getData().isEmpty()) {
					data_ = other.data_;
					onChanged();
				}
				if (!other.getInfo().isEmpty()) {
					info_ = other.info_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Object code_ = "";

			/**
			 * <code>string code = 1;</code>
			 */
			public String getCode() {
				Object ref = code_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					code_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <code>string code = 1;</code>
			 */
			public com.google.protobuf.ByteString
			getCodeBytes() {
				Object ref = code_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					code_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string code = 1;</code>
			 */
			public Builder setCode(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				code_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string code = 1;</code>
			 */
			public Builder clearCode() {

				code_ = getDefaultInstance().getCode();
				onChanged();
				return this;
			}

			/**
			 * <code>string code = 1;</code>
			 */
			public Builder setCodeBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				code_ = value;
				onChanged();
				return this;
			}

			private Object data_ = "";

			/**
			 * <code>string data = 2;</code>
			 */
			public String getData() {
				Object ref = data_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					data_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <code>string data = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getDataBytes() {
				Object ref = data_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					data_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string data = 2;</code>
			 */
			public Builder setData(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				data_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string data = 2;</code>
			 */
			public Builder clearData() {

				data_ = getDefaultInstance().getData();
				onChanged();
				return this;
			}

			/**
			 * <code>string data = 2;</code>
			 */
			public Builder setDataBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				data_ = value;
				onChanged();
				return this;
			}

			private Object info_ = "";

			/**
			 * <code>string info = 3;</code>
			 */
			public String getInfo() {
				Object ref = info_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs =
							(com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					info_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <code>string info = 3;</code>
			 */
			public com.google.protobuf.ByteString
			getInfoBytes() {
				Object ref = info_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
							com.google.protobuf.ByteString.copyFromUtf8(
									(String) ref);
					info_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string info = 3;</code>
			 */
			public Builder setInfo(
					String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				info_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string info = 3;</code>
			 */
			public Builder clearInfo() {

				info_ = getDefaultInstance().getInfo();
				onChanged();
				return this;
			}

			/**
			 * <code>string info = 3;</code>
			 */
			public Builder setInfoBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				info_ = value;
				onChanged();
				return this;
			}

			@Override
			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@Override
			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}


			// @@protoc_insertion_point(builder_scope:com.handsome.landlords.entity.ServerTransferDataProtoc)
		}

		// @@protoc_insertion_point(class_scope:com.handsome.landlords.entity.ServerTransferDataProtoc)
		private static final com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc();
		}

		public static com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<ServerTransferDataProtoc>
				PARSER = new com.google.protobuf.AbstractParser<ServerTransferDataProtoc>() {
			@Override
			public ServerTransferDataProtoc parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new ServerTransferDataProtoc(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<ServerTransferDataProtoc> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<ServerTransferDataProtoc> getParserForType() {
			return PARSER;
		}

		@Override
		public com.handsome.landlords.entity.ServerTransferData.ServerTransferDataProtoc getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
			internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
			descriptor;

	static {
		String[] descriptorData = {
				"\n\036ServerTransferDataProtoc.proto\022\037org.ni" +
						"co.ratel.landlords.entity\"D\n\030ServerTrans" +
						"ferDataProtoc\022\014\n\004code\030\001 \001(\t\022\014\n\004data\030\002 \001(" +
						"\t\022\014\n\004info\030\003 \001(\tB5\n\037com.handsome.landlo" +
						"rds.entityB\022ServerTransferDatab\006proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[]{
						}, assigner);
		internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_descriptor =
				getDescriptor().getMessageTypes().get(0);
		internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_fieldAccessorTable = new
				com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_org_nico_ratel_landlords_entity_ServerTransferDataProtoc_descriptor,
				new String[]{"Code", "Data", "Info",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
